### PR TITLE
Truncate era dd eds

### PR DESCRIPTION
**Pull request by kyleredilla**
This PR has changes to the degree day preprocessing notebook with the main change being a truncation of the input years used for ERA-Interim to 1980-2009.

To test, use the new draft geospatial conda env for SNAP geoprocessing pipelines. I.e., use the `environment.yml` file in the `add_conda_env` branch of the `snap-geo` repo [(here)](https://github.com/ua-snap/snap-geo/blob/add_conda_env/environment.yml) to create a conda environment for testing this notebook in.

Make sure the preprocessing notebook runs following instructions and the files import as expected. 

This pushes us further towards completing #51 but does not quite close it until we get the new coverages imported into Zeus.

### CODE REVIEW

**Review by cstephen — APPROVED** [review]
I ran this notebook successfully and it produced the expected outputs. I ran into a couple small snags along the way, not necessarily related to the changes in this PR, and not showstoppers:

- If you don't set the `NCORES` environment variable, it fails to default to 32:
  ```
  ---> 16 ncores = int(os.getenv("NCORES")) or 32
  ...

  TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
  ```
- When I created the `snap-geo` conda environment from the snap-geo repo's `environment.yml`, it wasn't able to install `ipykernel`. I fixed this by installing an older version. I'll make a ticket for this in the snap-geo repo.

**Comment by charparr** [comment]
Wow I let this go a bit stale! Sorry about that - looking now. @cstephen what version of `ipykernel` worked to build the env? I'm hitting what is likely the same issue via a lengthy attempt by conda to resolve the conflicts.

**Comment by cstephen** [comment]
@charparr Downgrading `ipykernel` to 6.15.2 in `environment.yml` is what worked for me. Kyle fixed up the `add_conda_env` branch of the snap-geo repo to reflect this:

https://github.com/ua-snap/snap-geo/commit/89b458b1c766bdbcf121ef047a6f0caa5f6ca3e2

**Comment by charparr** [comment]
Whoop! I obviously missed that commit, thanks. I'm attempting to build from that version but still getting stuck in an endless conflict resolve attempt. I'm not sure what's up but I may just nuke + reinstall my conda on Atlas.

**Comment by kyleredilla** [comment]
Hey @charparr are you trying to create the conda environment on the login node or a compute node?

**Comment by charparr** [comment]
@kyleredilla I'm trying from a compute node on Atlas. I wiped and re-installed conda. I get to here 
image
and then it resolves conflicts for an hour plus and ultimately fails. I've seen conda take a long time to create and resolve environments but this feels a little different.

**Comment by kyleredilla** [comment]
Dang! This is happening to me now too in trying to create this env. I do not remember bumping into any issues with conflicts previously. Maybe conda updated dependencies or dropped something, I have no idea. I will reconstruct this env spec with one that works and ping here when that's done.

**Comment by charparr** [comment]
Wow! Yeah I tried building with a fresh conda (seemed like a good way to start 2023) and it had no impact. The fact that you and Craig were able to build, but I couldn't, and now you can't either, definitely makes me suspect some upstream dependency change that now cannot be reconciled.

**Comment by kyleredilla** [comment]
Okay there is a new version of the `environment.yml` file in the `add_conda_env` branch of the `snap-geo` repo. This one seemed to `create` in under 10 minutes I think, so let me know if things are taking much longer than that (or if it doesn't work at all, of course).

**Comment by charparr** [comment]
Thanks Kyle - his `.yml` worked with about the same ~10 minute build time. Onward!

**Comment by charparr** [comment]
After a classic Python env kerfuffle I've executed the cells in this notebook! The notebook performs as expected and the resulting files are successful test ingest ingredients on Apollo.

**Review by charparr — APPROVED** [review]

**Pull request merged**
