### PR TITLE
Arctic eds mean annual temp

### PR DESCRIPTION
**Pull request by kyleredilla**
This PR contains a preprocessing notebook and ingest recipe for a new `mean_annual_temp` coverage to supply the data for the forthcoming "Mean Annual Temperature" plate of the Arctic EDS.

This coverage contains historical and projected mean annual temperature data derived from SNAP downscaled CRU-TS40 and CMIP5 datasets. No styles are tracked here at this time. This coverage has not yet been implemented on Zeus. Copies of the necessary ingest data exist on Atlas at `/atlas_scratch/cparr4/rasdaman_prod`

The recipes in this PR are good examples for ingesting big GeoTIFF stacks that use a "real" time axis.

### CODE REVIEW

**Review by cstephen — COMMENTED** [review]
I got the new `annual_mean_tas_preprocessing.ipynb` Jupyter Notebook running on Atlas and everything seems to work as expected, except for the last step where it attempts to generate histograms. I get this error message:

```
File ~/miniconda3/envs/jupyter/lib/python3.9/site-packages/numpy/lib/histograms.py:315, in _get_outer_edges(a, range)
    312         raise ValueError(
    313             'max must be larger than min in range parameter.')
    314     if not (np.isfinite(first_edge) and np.isfinite(last_edge)):
--> 315         raise ValueError(
    316             "supplied range of [{}, {}] is not finite".format(first_edge, last_edge))
    317 elif a.size == 0:
    318     # handle empty arrays. Can't determine range, so use 0-1.
    319     first_edge, last_edge = 0, 1

ValueError: supplied range of [-inf, 13.699999809265137] is not finite
```

The raster images in the previous step show correctly, however, so I'm surprised the histograms are failing.

**Comment by kyleredilla** [comment]
Hey @cstephen could you post a screenshot of the "maps" that worked before you tried executing the histograms cell?

**Comment by cstephen** [comment]
Here are the map plots that work, before the histogram step that fails:

image

**Comment by kyleredilla** [comment]
image

@cstephen I have not been able to reproduce the data produced from your execution of the notebook. It looks like it is creating `-inf` values where the nodata values should be. 

Also, the resulting summarized arrays are different:

image

I made a small change, I don't think it will make a difference, but I wonder if you could try running the notebook again when you get the chance? I'm not sure what else to try on my end.

**Comment by cstephen** [comment]
I pulled down the latest changes to this branch and I'm getting a bunch of these warnings now:

> RuntimeWarning: overflow encountered in reduce

image

I'm guessing these warnings are related to the differences in my output files. I'll see if I can fix this on my end since it sounds like something is wrong with my environment. Like before, the maps are displayed properly, but the histograms are showing the same error.

The unique file sizes are different this time, too, but still do not match the expected file sizes:

image

**Pull request merged**
